campbell_header.settings:
  type: config_object
  label: 'Campbell Header settings'
  mapping:
    phone:
      type: text
    email:
      type: email
    hours:
      type: text
    cta_text:
      type: text
    cta_url:
      type: text
    facebook:
      type: text
    instagram:
      type: text
    linkedin:
      type: text
    youtube:
      type: text
