block.settings.campbell_main_header:
  type: mapping
  label: 'Campbell Main Header settings'
  mapping:
    logo_src:
      type: string
      label: 'Logo URL'
    logo_alt:
      type: string
      label: 'Logo alt text'
    cta_label:
      type: string
      label: 'CTA button text'
    cta_path:
      type: string
      label: 'CTA link'
    cta_new_tab:
      type: boolean
      label: 'Open CTA in new tab'
    show_phone:
      type: boolean
      label: 'Show phone number'
    phone_text:
      type: string
      label: 'Phone text'
    menu_name:
      type: string
      label: 'Primary menu machine name'
